// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// send_SIGINT
bool send_SIGINT(long long unsigned pid);
RcppExport SEXP _RedisParam_send_SIGINT(SEXP pidSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< long long unsigned >::type pid(pidSEXP);
    rcpp_result_gen = Rcpp::wrap(send_SIGINT(pid));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RedisParam_send_SIGINT", (DL_FUNC) &_RedisParam_send_SIGINT, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_RedisParam(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
